import { Sofia_Sans } from "next/font/google";
import "./globals.css";
import "@/app/homepage.scss";

const sofia = Sofia_Sans({
  weight: ["400", "700", "500", "600"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sofia.className} suppressHydrationWarning={true}>
        <div className="page-container">{children}</div>
      </body>
    </html>
  );
}
